# Generated by Django 4.0.5 on 2022-06-14 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='animals',
        ),
    ]
