# Generated by Django 4.0.5 on 2022-06-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0002_remove_characteristic_animals'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='characteristics',
            field=models.ManyToManyField(related_name='animals', to='characteristics.characteristic'),
        ),
    ]
